volunteer_mgmt/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
import volunteers.views as views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'volunteer_mgmt.views.home', name='home'),
    # url(r'^volunteer_mgmt/', include('volunteer_mgmt.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    #url(r'^volunteers/', include('volunteers.urls', namespace='volunteers')),
    #url(r'^accounts/login/.*$', 'django.contrib.auth.views.login'),
    #url(r'^volunteers/LogOut/$', 'volunteers.views.logOut'),
    #url(r'^AddTasks/$', views.add_tasks, name='add_tasks'),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # Userena urls:
    url(r'^$', 'volunteers.views.promo', name='promo'),
    url(r'^faq/', 'volunteers.views.faq', name='faq'),
    url(r'^volunteers/signup', 'volunteers.views.signup', name='signup'),
    url(r'^volunteers/(?P<username>(?!signout|signup|signin)[\.\w-]+)/$', 'volunteers.views.profile_detail', name='profile_detail'),
    url(r'^volunteers/(?P<username>[\.\w-]+)/edit/$', 'volunteers.views.profile_edit', name='userena_profile_edit'),
    url(r'^volunteers/page/(?P<page>[0-9]+)/$', views.ProfileListView.as_view(), name='userena_profile_list_paginated'),
    url(r'^volunteers/$', views.ProfileListView.as_view(), name='userena_profile_list'),
    url(r'^volunteers/', include('userena.urls')),
    url(r'^messages/', include('userena.contrib.umessages.urls')),
    # other urls:
    url(r'^tasks/(?P<username>[\.\w-]+)', 'volunteers.views.task_list_detailed', name='task_list_detailed'),
    url(r'^task/(?P<task_id>\d+)/$', 'volunteers.views.task_detailed', name='task_detailed'),
    url(r'^talk/(?P<talk_id>\d+)/$', 'volunteers.views.talk_detailed', name='talk_detailed'),
    url(r'^tasks/', 'volunteers.views.task_list', name='task_list'),
    url(r'^talks/', 'volunteers.views.talk_list', name='talk_list'),
    url(r'^category_schedule/', 'volunteers.views.category_schedule_list', name='category_schedule_list'),
    url(r'^task_schedule/(?P<template_id>\d+)/$', 'volunteers.views.task_schedule', name='task_schedule'),
    url(r'^task_schedule_csv/(?P<template_id>\d+)/$', 'volunteers.views.task_schedule_csv', name='task_schedule_csv'),


) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

volunteers/urls.py
from django.conf.urls import patterns, include, url
from volunteers import views

urlpatterns = patterns('',
    #url(r'^$', views.index, name='volunteer_index'),
    #url(r'^(?P<volunteer_id>\d+)/$', views.volunteer_detail, name='volunteer_detail'),
    #url(r'^AddTasks/$', views.add_tasks, name='add_tasks'),
    #url(r'^(?P<volunteer_id>\d+)/edit/$', views.volunteer_edit, name='volunteer_edit'),
)

volunteers/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db import models
from django.utils.translation import ugettext_lazy as _
from userena.models import UserenaLanguageBaseProfile

import datetime
# from dateutil import relativedelta
import hashlib
import httplib
import os
import urllib
import vobject
import xml.etree.ElementTree as ET


# Parse dates, times, DRY
def parse_datetime(date_str, format='%Y-%m-%d'):
    return datetime.datetime.strptime(date_str, format)


def parse_date(date_str, format='%Y-%m-%d'):
    return parse_datetime(date_str, format).date()


def parse_time(date_str, format='%H:%M'):
    return parse_datetime(date_str, format).time()


# More DRY: given a start hour and duration, return start and end time.
def parse_hour_duration(start_str, duration_str, format='%H:%M'):
    start = datetime.datetime.strptime(start_str, format)
    dur_tm = datetime.datetime.strptime(duration_str, format)
    duration = datetime.timedelta(hours=dur_tm.hour, minutes=dur_tm.minute, seconds=dur_tm.second)
    end = start + duration
    start_tm = datetime.time(hour=start.hour, minute=start.minute, second=start.second)
    end_tm = datetime.time(hour=end.hour, minute=end.minute, second=end.second)
    return(start_tm, end_tm)


# Helper model
class HasLinkField():
    def link(self):
        return 'Link'


# Create your models here.

class Edition(models.Model):
    class Meta:
        verbose_name = _('Edition')
        verbose_name_plural = _('Editions')
        ordering = ['-start_date']

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=128)
    start_date = models.DateField()
    end_date = models.DateField()
    visible_from = models.DateField()
    visible_until = models.DateField()

    @classmethod
    def get_current(cls):
        retval = False
        today = datetime.date.today()
        current = cls.objects.filter(visible_from__lte=today, visible_until__gte=today)
        if current:
            retval = current[0].id
        return retval

    @classmethod
    def penta_create_or_update(cls, xml):
        ed_name = xml.find('title').text
        start_date = parse_date(xml.find('start').text)
        end_date = parse_date(xml.find('end').text)
        visible_from = datetime.date(year=start_date.year - 1, month=8, day=1)
        visible_until = datetime.date(year=start_date.year, month=7, day=31)
        editions = cls.objects.filter(name=ed_name)
        if len(editions):
            edition = editions[0]
        else:
            edition = cls(name=ed_name)  # create if required
        edition.start_date = start_date
        edition.end_date = end_date
        edition.visible_from = visible_from
        edition.visible_until = visible_until
        edition.save()
        return edition

    @classmethod
    def init_generic_tasks(cls):
        edition = cls.get_current()
        if edition:
            generic_task_tree = ET.parse('volunteers/init_data/generic_tasks.xml')
            generic_task_root = generic_task_tree.getroot()
            for task in generic_task_root.findall('task'):
                Task.create_from_xml(task, edition)

    @classmethod
    def sync_with_penta(cls):
        penta_url = settings.SCHEDULE_SYNC_URI
        response = urllib.urlopen(penta_url)
        penta_xml = response.read()
        root = ET.fromstring(penta_xml)
        ###########
        # Edition #
        ###########
        ed = root.find('conference')
        edition = cls.penta_create_or_update(ed)

        #########
        # Talks #
        #########
        days = root.findall('day')
        for day in days:
            day_date = parse_date(day.get('date'))
            rooms = day.findall('room')
            for room in rooms:
                room_name = room.get('name')
                # Lightning talks are done manually since the time slots are so small.
                needs_heralding = needs_video = room_name in ['Janson', 'K.1.105 (La Fontaine)']
                events = room.findall('event')
                for event in events:
                    talk = Talk.penta_create_or_update(event, edition, day_date)
                    ######################
                    # Tasks, if required #
                    ######################
                    if needs_heralding:
                        Task.create_or_update_from_talk(edition, talk, 'Heralding', [3, 2, 5])
                    if needs_video:
                        Task.create_or_update_from_talk(edition, talk, 'Video', [1, 1, 1])


class Track(models.Model):
    """
    A track is a collection of talks, grouped around one single
    concept or subject.
    """
    class Meta:
        verbose_name = _('Track')
        verbose_name_plural = _('Tracks')
        ordering = ['date', 'start_time', 'title']

    def __unicode__(self):
        return self.title

    title = models.CharField(max_length=128)
    description = models.TextField(blank=True, null=True)
    edition = models.ForeignKey(Edition, default=Edition.get_current)
    date = models.DateField()
    start_time = models.TimeField()
    # end_time = models.TimeField()

class Room(models.Model):
    """
    A room is a collection of talks, grouped by where they are physically taking place
    """
    class Meta:
        verbose_name = _('Room')
        verbose_name_plural = _('Rooms')
        ordering = ['name']

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=128)
    edition = models.ForeignKey(Edition, default=Edition.get_current)

class Talk(models.Model, HasLinkField):
    class Meta:
        verbose_name = _('Talk')
        verbose_name_plural = _('Talks')
        ordering = ['date', 'start_time', '-end_time', 'title']

    def __unicode__(self):
        return self.title

    ext_id = models.CharField(max_length=16)  # ID from where we synchronise
    track = models.ForeignKey(Track)
    room = models.ForeignKey(Room)
    title = models.CharField(max_length=256)
    speaker = models.CharField(max_length=128)
    description = models.TextField()
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    volunteers = models.ManyToManyField('Volunteer', through='VolunteerTalk', blank=True, null=True)

    def assigned_volunteers(self):
        return self.volunteers.count()

    @classmethod
    def penta_create_or_update(cls, xml, edition, day_date):
        event_id = xml.get('id')
        talks = cls.objects.filter(ext_id=event_id)
        if len(talks):
            talk = talks[0]
        else:
            talk = cls(ext_id=event_id)
        start_txt = xml.find('start').text
        dur_txt = xml.find('duration').text
        (talk_start, talk_end) = parse_hour_duration(start_txt, dur_txt)
        track_name = xml.find('track').text
        tracks = Track.objects.filter(title=track_name, edition=edition)
        if len(tracks):
            track = tracks[0]
        else:
            track = Track(title=track_name, edition=edition, date=day_date, start_time=talk_start)
        if day_date < track.date:
            track.date = day_date
        if talk_start < track.start_time:
            track.start_time = talk_start
        track.save()
        talk.track = track
        talk.title = xml.find('title').text
        talk.description = xml.find('description').text or ''
        talk.date = day_date
        (talk.start_time, talk.end_time) = (talk_start, talk_end)
        persons = xml.find('persons')
        people = []
        if len(persons):
            for person in persons.findall('person'):
                people.append(person.text)
            speakers_str = ', '.join(people)
            talk.speaker = speakers_str
        talk.save()
        return talk


class TaskCategory(models.Model, HasLinkField):
    """
    Categories are things like buildup, cleanup, moderation, ...
    """
    class Meta:
        verbose_name = _('Task Category')
        verbose_name_plural = _('Task Categories')
        ordering = ['name']

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=50)
    description = models.TextField()
    volunteers = models.ManyToManyField('Volunteer', through='VolunteerCategory', blank=True, null=True)
    active = models.BooleanField(default=True)

    def assigned_volunteers(self):
        return self.volunteer_set.count()

    @classmethod
    def create_or_update_named(cls, name):
        categories = TaskCategory.objects.filter(name=name)
        if len(categories):
            category = categories[0]
        else:
            category = cls(name=name)
            category.save()
        return category


class TaskTemplate(models.Model):
    """
    A task template contains all data about a task that isn't task specific.
    For example, cleanup can happen in multiple locations or at multiple times.
    Not sure we need this, but it seemed like a good thing to have when I wrote
    down the DB model. ;)
    """
    class Meta:
        verbose_name = _('Task Template')
        verbose_name_plural = _('Task Templates')
        ordering = ['name']

    def __unicode__(self):
        return self.name

    name = models.CharField(max_length=50)
    description = models.TextField()
    category = models.ForeignKey(TaskCategory)

    @classmethod
    def create_or_update_named(cls, name):
        templates = cls.objects.filter(name=name)
        if len(templates):
            template = templates[0]
        else:
            template = cls(name=name)
            category = TaskCategory.create_or_update_named(name)
            template.category = category
            template.save()
        return template


class Task(models.Model, HasLinkField):
    """
    Contains the specifics of an instance of a task. It's based on a task

volunteers/templates/volunteers/category_schedule_list.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load volunteer_extras %}

{% block content_title %}<h2 class="content-title">{% trans 'Categories' %}</h2>{% endblock %}

{% block content %}
    {% for category, templates in categories.items %}
    <h2>Category: {{ category.name }}</h2>
    <ul>
        {% for template in templates %}

        <li><a href="{% url 'task_schedule' template.id %}" title="View Schedule">{{ template.name }}</a></li>
        {% endfor %}
    </ul>
    <br/>
    {% endfor %}
{% endblock %}

volunteers/templates/volunteers/talk_detailed.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load volunteer_extras %}

{% block content_title %}<h2 class="content-title">{% trans 'Talk' %}</h2>{% endblock %}

{% block content %}
<form class="talk_list">{% csrf_token %}
    <fieldset>
        <legend class="talk_list">{% trans 'Talk' %}</legend>
        <table class="talk_list">
            <tr>
                <th width="20%">{% trans 'When' %}</th>
                <th width="40%">{% trans 'Title' %}</th>
                <th width="20%">{% trans 'Attending' %}</th>
            </tr>
            <tr>
                <td>{{ talk.date|date:"D" }}, {{ talk.start_time|time:"H:i" }} - {{ talk.end_time|time:"H:i" }}</td>
                <td>{{ talk.title }}</td>
                <td>
                {% for volunteer in talk.volunteers.all %}
                    {{ volunteer.user.first_name }} {{ volunteer.user.last_name }}, 
                {% endfor %}
            </tr>
        </table>
        <br>
    </fieldset>
</form>

<div id="dialog" title="Talk"></div>
{% endblock %}

volunteers/templates/volunteers/talks.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load volunteer_extras %}

{% block content_title %}<h2 class="content-title">{% trans 'Talks' %}</h2>{% endblock %}

{% block content %}
<form class="task_list" action="/talks/" method="post">{% csrf_token %}
    {% for track, talks in tracks.items %}
    <fieldset>
        <legend class="talk_list">{{ track }}</legend>
        <table class="talk_list">
            <thead>
                <tr>
                    <th>{% trans "I'm Going" %}!</th>
                    <th>{% trans 'Title' %}</th>
                    <th>{% trans 'When' %}</th>
                    <th>{% trans 'Speaker' %}</th>
                    <th class="numeric">{% trans 'Attending' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for talk in talks %}
                <tr>
                    <td data-title="{% trans 'Going' %}!"><input type="checkbox" name="talk" value="{{ talk.id }}" {{ checked|get_item:talk.id }} /></td>
                    <td data-title="{% trans 'Title' %}"><a href="{% url 'talk_detailed' talk.id %}">{{ talk.title }}</a></td>
                    <td data-title="{% trans 'When' %}">{{ talk.date|date:"D" }}, {{ talk.start_time|time:"H:i" }} - {{ talk.end_time|time:"H:i" }}</td>
                    <td data-title="{% trans 'Speaker' %}">{{ talk.speaker }}</td>
                    <td data-title="{% trans 'Attending' %}" class="numeric talk-volunteers" title="Attending:<br/>{% for volunteer in talk.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}">{{ talk.assigned_volunteers }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </fieldset>
    {% endfor %}
    <input type="submit" value="{% trans "Save changes" %}" />
</form>

<div id="dialog" title="Talk"></div>

{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="{% url 'userena_profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
        {% endif %}

        <span class="current">
            {% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="{% url 'userena_profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}

volunteers/templates/volunteers/task_detailed.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load volunteer_extras %}

{% block content_title %}<h2 class="content-title">{% trans 'Task' %}</h2>{% endblock %}

{% block content %}
<form class="task_list">{% csrf_token %}
    <fieldset>
        <legend class="task_list">{% trans 'Task' %}</legend>
        <table class="task_list">
            <tr>
                <th width="20%">{% trans 'When' %}</th>
                <th width="40%">{% trans 'Title' %}</th>
                <th width="20%">{% trans 'Attending' %}</th>
                <th width="20%">{% trans 'Talk' %}</th>
            </tr>
            <tr>
                <td>{{ task.date|date:"D" }}, {{ task.start_time|time:"H:i" }} - {{ task.end_time|time:"H:i" }}</td>
                <td>{{ task.name }}</td>
                <td>
                    {% if user.is_authenticated %}
                    {% for volunteer in task.volunteer_set.all %}
                        <a href="{% url 'profile_detail' volunteer.user.username %}">{{ volunteer.user.first_name }} {{ volunteer.user.last_name }},</a>
                    {% endfor %}
                    {% else %}
                        {{ task.volunteer_set.count}}/{{ task.nbr_volunteers }}
                    {% endif%}
                <td>{{ task.talk }}</td>
            </tr>
            <tr>
                <th colspan="4" style="border-bottom: none;">&nbsp;</th>
            </tr>
            <tr>
                <td colspan="4">{{ task.description|linebreaksbr }}</td>
            </tr>
        </table>
        <br>
    </fieldset>
</form>

<div id="dialog" title="Task"></div>
{% endblock %}

volunteers/templates/volunteers/tasks.html
{% extends 'userena/base_userena.html' %}
{% load i18n %}
{% load url from future %}
{% load volunteer_extras %}

{% block content_title %}<h2 class="content-title">{% trans 'Tasks' %}</h2>{% endblock %}

{% block content %}
{% if user.is_authenticated %}<a class="larger-font" href="{% url 'task_list_detailed' user.username %}" title="View schedule">View your schedule</a>{% endif %}
<form class="task_list" action="{% url 'task_list' %}" method="post">{% csrf_token %}
    {% if is_dr_manhattan %}
    <fieldset>
        <legend class="task_list">We seem to have a bit of a problem here...</legend><br/>
        <table>
            <tr>
                <td><img src="http://nighty.safehex.be/linked_pics/dr_manhattan.png"/></td>
                <td width="20px;">&nbsp;</td>
                <td style="vertical-align: top;">
                    Unless you look like the guy on the left, odds are you're not actually capable
                    of being in two different locations at the same time. So it might be wise to take
                    action on the tasks below...
                </td>
                <td width="50%">&nbsp;</td>
            </tr>
        </table><br/>
        <table class="task_list">
            <thead>
                <tr class="table_top_alert">
                    <th width="10%">{% trans "I'm in" %}!</th>
                    <th width="55%">{% trans 'Task' %}</th>
                    <th width="20%">{% trans 'When' %}</th>
                    <th width="15%">{% trans 'Volunteers' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for task_set in dr_manhattan_task_sets %}
                    <tr class="task_set_alert">
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">Problematic tasks #{{ forloop.counter }}:</th>
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                    </tr>
                    {% for task in task_set %}
                    <tr>
                        <td {% if user.is_authenticated %}data-title="{% trans 'I am in' %}!"{% endif %}>{% if user.is_authenticated %}<input type="checkbox" name="task" value="{{ task.id }}" {{ checked|get_item:task.id }} />{% endif %}</td>
                        {% if attending|get_item:task.id == True %}
                        <td class="task-name special-task">{{ task.name }} <span class="small_note">(Hey, you're attending this!)</span></td>
                        {% else %}
                        <td data-title="{% trans 'Task' %}" class="task-name"><a href="{% url 'task_detailed' task.id %}">{{ task.name }}</a></td>
                        {% endif %}
                        <td data-title="{% trans 'When' %}" >{{ task.date|date:"D" }}, {{ task.start_time|time:"H:i" }} - {{ task.end_time|time:"H:i" }}</td>
                        {% if task.assigned_volunteers == task.nbr_volunteers_max %}
                        <td data-title="{% trans 'Volunteers' %}" class="task-volunteers blue" title="{% trans 'Full' %}
                        {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                        {% elif task.assigned_volunteers >= task.nbr_volunteers %}
                        <td data-title="{% trans 'Volunteers' %}" class="task-volunteers green" title="{% trans 'Staffed' %}
                        {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                        {% elif task.assigned_volunteers >= task.nbr_volunteers_min %}
                        <td data-title="{% trans 'Volunteers' %}" class="task-volunteers gray" title="{% trans 'Manageable' %}
                        {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                        {% else %}
                        <td data-title="{% trans 'Volunteers' %}" class="task-volunteers red" title="{% trans 'More volunteers needed' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %} {% endif%}">
                        {% endif %}
                        {{task.assigned_volunteers}}/{{ task.nbr_volunteers }}</td>
                    </tr>
                    {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </fieldset>
    {% endif %}
    {% for title, days in tasks.items %}
    <fieldset>
        <legend class="task_list">{% trans title %} <span style="font-size: small; font-weight: normal;">
            {% if user.is_authenticated %}{% if title == 'preferred tasks' %}
            (<a class="larger-font" href="{% url 'userena_profile_edit' user.username %}">{% trans 'Change in profile' %}</a>)
            {% endif %}{% endif %}
        </span></legend>
        <table class="task_list">
            <thead>
                <tr class="table_top">
                    <th width="10%">{% trans "I'm in" %}!</th>
                    <th width="55%">{% trans 'Task' %}</th>
                    <th width="20%">{% trans 'When' %}</th>
                    <th width="15%">{% trans 'Volunteers' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for day, categories in days.items %}
                {% if categories.items %}
                {% ifchanged %}
                {% else %}
                <tr class="row-hide">
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                </tr>
                {% endifchanged %}
                <tr class="day">
                    <th class="no_vert_border">{{ day|date:"l" }}</th>
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                    <th class="no_vert_border">&nbsp;</th>
                </tr>
                    {% for category, category_tasks in categories.items %}
                    {% if category_tasks %}
                    {% ifchanged %}
                    {% else %}
                    <tr class="row-hide">
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                    </tr>
                    {% endifchanged %}
                    <tr class="category">
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">{{ category.name }}</th>
                        <th class="no_vert_border">&nbsp;</th>
                        <th class="no_vert_border">&nbsp;</th>
                    </tr>
                        {% for task in category_tasks %}
                        <tr>
                            <td {% if user.is_authenticated %}data-title="{% trans 'I am in' %}!"{% endif %}>{% if user.is_authenticated %}<input type="checkbox" name="task" value="{{ task.id }}" {{ checked|get_item:task.id }} />{% endif %}</td>
                            {% if attending|get_item:task.id == True %}
                            <td class="task-name special-task">{{ task.name }} <span class="small_note">(Hey, you're attending this!)</span></td>
                            {% else %}
                            <td data-title="{% trans 'Task' %}" class="task-name"><a href="{% url 'task_detailed' task.id %}">{{ task.name }}</a></td>
                            {% endif %}
                            <td data-title="{% trans 'When' %}">{{ task.date|date:"D" }}, {{ task.start_time|time:"H:i" }} - {{ task.end_time|time:"H:i" }}</td>
                            {% if task.assigned_volunteers == task.nbr_volunteers_max %}
                            <td data-title="{% trans 'Volunteers' %}" class="task-volunteers blue" title="{% trans 'Full' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                            {% elif task.assigned_volunteers >= task.nbr_volunteers %}
                            <td data-title="{% trans 'Volunteers' %}" class="task-volunteers green" title="{% trans 'Staffed' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                            {% elif task.assigned_volunteers >= task.nbr_volunteers_min %}
                            <td data-title="{% trans 'Volunteers' %}" class="task-volunteers gray" title="{% trans 'Manageable' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                            {% else %}
                            <td data-title="{% trans 'Volunteers' %}" class="task-volunteers red" title="{% trans 'More volunteers needed' %}
                            {% if user.is_authenticated %}<br/><br/>Signed up:<br/>{% for volunteer in task.volunteers.all %}* {{ volunteer.user.first_name }} {{ volunteer.user.last_name}} ({{ volunteer.user }})<br/>{% endfor %}{% endif %}">
                            {% endif %}
                            {{task.assigned_volunteers}}/{{ task.nbr_volunteers }}</td>
                        </tr>
                        {% endfor %}
                    {% endif %}
                    {% endfor %}
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
        <br>
    </fieldset>
    {% endfor %}
    {% if user.is_authenticated %}
    <input type="submit" value="{% trans "Save changes" %}" />
    {% endif %}
</form>

<div id="dialog" title="Task"></div>

{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="{% url 'userena_profile_list_paginated' page_obj.previous_page_number %}">{% trans 'previous' %}</a>
        {% endif %}

        <span class="current">
            {% trans 'Page' %} {{ page_obj.number }} {% trans 'of' %} {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="{% url 'userena_profile_list_paginated'  page_obj.next_page_number %}">{% trans 'next' %}</a>
        {% endif %}
    </span>
</div>
{% endif %}
{% endblock %}